import React from "react";
import Card from "./components/Card";

const App = () => {
  const data = [
    {
      id: 1,
      name: "Wade Wilson",
      role: "UI/UX Designer",
      company: "Epic Coders",
      rate: "$55/hr",
      status: true,
      skills: ["UI", "UX", "Photoshop"],
      extraSkills: 4,
      desc: "Experienced UI/UX designer with strong portfolio.",
      img: "https://randomuser.me/api/portraits/men/1.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 2,
      name: "Maria Petrescu",
      role: "Mobile Developer",
      company: "Freelancer",
      rate: "$32/hr",
      status: false,
      skills: ["PHP", "Android", "iOS"],
      extraSkills: 2,
      desc: "Android & iOS developer with 6 years experience.",
      img: "https://randomuser.me/api/portraits/women/2.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 3,
      name: "Alexandra Morgan",
      role: "Mobile Designer",
      company: "Freelancer",
      rate: "$42/hr",
      status: true,
      skills: ["PHP", "Android", "iOS"],
      extraSkills: 12,
      desc: "Dedicated mobile designer for modern apps.",
      img: "https://randomuser.me/api/portraits/women/3.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 4,
      name: "John Smith",
      role: "Frontend Developer",
      company: "Tech Corp",
      rate: "$40/hr",
      status: false,
      skills: ["React", "JS", "CSS"],
      extraSkills: 3,
      desc: "Frontend dev specializing in React apps.",
      img: "https://randomuser.me/api/portraits/men/4.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 5,
      name: "Emma Watson",
      role: "UI Designer",
      company: "Creative Studio",
      rate: "$38/hr",
      status: true,
      skills: ["Figma", "UI", "Branding"],
      extraSkills: 5,
      desc: "Creative UI designer with modern design sense.",
      img: "https://randomuser.me/api/portraits/women/5.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 6,
      name: "David Miller",
      role: "Backend Developer",
      company: "ServerX",
      rate: "$50/hr",
      status: true,
      skills: ["Node", "MongoDB", "API"],
      extraSkills: 4,
      desc: "Backend expert with scalable API experience.",
      img: "https://randomuser.me/api/portraits/men/6.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 7,
      name: "Sophia Lee",
      role: "Full Stack Developer",
      company: "Startup Inc",
      rate: "$60/hr",
      status: false,
      skills: ["React", "Node", "DB"],
      extraSkills: 6,
      desc: "Full stack dev building end-to-end apps.",
      img: "https://randomuser.me/api/portraits/women/7.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 8,
      name: "Chris Evans",
      role: "UI Engineer",
      company: "DesignHub",
      rate: "$45/hr",
      status: true,
      skills: ["UI", "CSS", "Animations"],
      extraSkills: 2,
      desc: "UI engineer focused on smooth UX.",
      img: "https://randomuser.me/api/portraits/men/8.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 9,
      name: "Olivia Brown",
      role: "Product Designer",
      company: "Innovate Ltd",
      rate: "$48/hr",
      status: false,
      skills: ["UX", "Research", "Wireframe"],
      extraSkills: 3,
      desc: "Product designer with user-first mindset.",
      img: "https://randomuser.me/api/portraits/women/9.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 10,
      name: "Daniel Craig",
      role: "Software Engineer",
      company: "DevWorks",
      rate: "$52/hr",
      status: true,
      skills: ["Java", "Spring", "API"],
      extraSkills: 4,
      desc: "Experienced software engineer in backend systems.",
      img: "https://randomuser.me/api/portraits/men/10.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 11,
      name: "Isabella Garcia",
      role: "UX Researcher",
      company: "UX Lab",
      rate: "$35/hr",
      status: true,
      skills: ["Research", "Testing", "UX"],
      extraSkills: 2,
      desc: "UX researcher focused on usability testing.",
      img: "https://randomuser.me/api/portraits/women/11.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
    {
      id: 12,
      name: "Liam Johnson",
      role: "React Developer",
      company: "Frontend Co",
      rate: "$47/hr",
      status: false,
      skills: ["React", "Hooks", "Redux"],
      extraSkills: 5,
      desc: "React dev building fast web apps.",
      img: "https://randomuser.me/api/portraits/men/12.jpg",
      btnText: "View Profile",
      showDivider: true,
    },
  ];

  const cardData = data.map((item) => {
    return <Card key={item.id} {...item} />;
  });
  return (
    <div className="container">
      {cardData}
      {cardData}
    </div>
  );
};

export default App;
